---
- name : Clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"

- name : lighthouse-role
  src: git@github.com:alxcreate/lighthouse.git
  scm: git
  version: "1.0.0"

- name : vector-role
  src: git@github.com:alxcreate/vector.git
  scm: git
  version: "1.0.0"